name: Flutter CI/CD

on:
  push:
    branches:
      - main  # This will trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # This will trigger the workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for building the app
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Step 2: Set up Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v5
        with:
          flutter-version: stable  # Use the stable Flutter version

      # Step 3: Cache dependencies to speed up subsequent builds
      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}  # Cache based on pubspec.yaml

      # Step 4: Install Flutter dependencies
      - name: Install Dependencies
        run: flutter pub get
      
      # Step 5: Run tests to ensure code quality
      - name: Run Tests
        run: flutter test

      # Optional: Run Flutter Analyze for static code analysis
      - name: Analyze Code
        run: flutter analyze
